sudo: false

language: php
php:
 - 7.0

script: php -dphar.readonly=0 ./src/DevTools/ConsoleScript.php --make ./

deploy:
  - provider: releases
    api_key:
      secure: fd34bfe2c74818a4ede923e922d3408e614fdd11
    file: *.phar
    skip_cleanup: true
    on:
      tags: true
